### ISSUE TITLE
Apparently use-package needs 24.4

### ISSUE THREAD

**Issue by JJ** [hinrik/perl6-mode#15]
Is there any other way to use this without use-package?

**Comment by hinrik** [comment]
The README mentions how to install it manually from MELPA. But I haven't tested `perl6-mode` with anything older than 24.4, so I can't guarantee it'll work.

**Comment by JJ** [comment]
But can whatever is done via `use-pckage` be done in some other way? As far as I see it, `perl6-mode` does not have a problem, it is that single configuration line what seems to need it a specific emacs version.

**Comment by JJ** [comment]
Can you give a hint on how to use it without use-package so that I can test it myself?

**Comment by hinrik** [comment]
If you have installed it (e.g. with `M-x package-install RET perl6-mode`), then `perl6-mode` should be automatically activated on most Perl 6 source files. You can also manually turn it on with `M-x perl6-mode RET`.

**Comment by JJ** [comment]
Apparently I can't even install it if it's not from emacs 24.4, it issues an error if I do what you just said. Is it using some specific feature of that version?

**Comment by hinrik** [comment]
> Is it using some specific feature of that version?

Could be, I don't remember exactly. And I don't have an older emacs to test on. You could clone the repository and change your `load-path` (https://www.emacswiki.org/emacs/LoadPath) to load it directly from there and see whether it works.

**Comment by JJ** [comment]
Will try that. Thanks for the feedback.

**Comment by hadenpike** [comment]
Does this still depend on use-package? I cloned perl6-mode from Github and adjusted my configuration appropriately. It works just fine.

**Comment by hinrik** [comment]
It never depended on `use-package`. That's just one of the installation examples provided in the README.

**Comment by hadenpike** [comment]
The readme states, "this package requires GNU Emacs 24.4." use-package was the only dependency I could find. It runs fine in my Emacs 25.1. Am I missing something?

**Comment by npostavs** [comment]
@hadenpike In the Emacs world "requires Foo x.y" usually means "x.y or later".

**Comment by JJ** [comment]
I will simply close this. I am now running it in 25.1 without a problem.
