### ISSUE TITLE
Reference raku-mode on the README

### ISSUE THREAD

**Issue by matiaslina** [hinrik/perl6-mode#23]
Hi @hinrik ,

The `perl6-mode` is being renamed to `raku-mode`. There's a suggestion on https://github.com/Raku/raku-mode/issues/22 to mention `raku-mode` in this repo README since it's the original one and the old `perl6-mode` (https://github.com/perl6/perl6-mode) now redirects to https://github.com/Raku/raku-mode .

Would it be possible to make this changes?

Thanks!

**Comment by hinrik** [comment]
Done!

**Comment by matiaslina** [comment]
Thanks! :)
