### ISSUE TITLE
Hyper ops << act as quotes

### ISSUE THREAD

**Issue by nd3i** [hinrik/perl6-mode#8]
Hyper op: << or « act as open-quote: no highlighting until a matching >> or »

Hyper-unary seems ok: +<< ... doesn't quote.

**Comment by hinrik** [comment]
Can you post a code example that exhibits this problem?

**Comment by autark** [comment]
Not OP, but I came across the same problem with this statement:

$a <<*<< $b;

**Comment by nd3i** [comment]
So sorry. I never saw your request for an example. I only just now got the closure notification.

Oh well, thanks for following up. Good to get it fixed.

**Comment by hinrik** [comment]
No worries. :)
