### ISSUE TITLE
Less than or equal operator not being parsed correctly.

### ISSUE THREAD

**Issue by bstamour** [hinrik/perl6-mode#9]
The following program demonstrates

use v6;
my $v1 = 2;
my $v2 = 3;
if $v1 <= $v2 { say 'what'; }

Everything after "<=" does not parse correctly, leading to indentation breaking.

Wrapping the conditional with parens does not fix the issue either.

**Comment by dct** [comment]
Adding (looking-at (rx-to-string `(char "="))) to perl6-font-lock.el:388 seems to fix it for me but I don't know anything about the surrounding code.
